### ISSUE TITLE
GD-334: Provide a GitHub action to run `GdUnit` tests that you can include directly into your CI workflow.

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#334]
**Is your feature request related to a problem? Please describe.**
Provide a GitHub action to run GdUnit tests.

**Describe the solution you'd like**
Instead of having to manually build the setup to run tests, it would be nice to use a pre-built GitHub action.

```
      - name: run gdunit tests
        uses: MikeSchulze/gdunit@v4.2
        timeout-minutes: 8 # set your expected test timeout
        with:
          godot-version: '4.2.1'
          godot-status: 'stable'
          godot-mono: false
          paths: |
                 "res://my_project_a/tests"
                 "res://my_project_b/tests"
          report-name: "test_report"
```
