### ISSUE TITLE
GD-409: `CmdTool` do not skip test suites when using `--conf <runner.cfg>`

### ISSUE THREAD

**Issue by RandallLiuXin** [MikeSchulze/gdUnit4#409]
### The used GdUnit4 version

4.2.2 (Latest Release)

### The used Godot version

v4.2.2-stable

### Operating System

ubuntu-latest

### Describe the bug

I want to skip some tests on my CI.
```
      - name: 'Test GdUnit4 - Godot_${{ inputs.godot-version }}-${{ inputs.godot-status }}'
        uses: MikeSchulze/gdUnit4-action@v1.0.5
        with:
          godot-version: ${{ inputs.godot-version }}
          godot-status: ${{ inputs.godot-status }}
          version: v4.2.4
          paths: |
            res://test/
          timeout: 10
          arguments: |
            -conf res://test/gdunit_ci.cfg
          report-name: report_Godot${{ inputs.godot-version }}-${{ inputs.godot-status }}.xml
```
and here is my cfg file.
```
{"included":{"res:///test":[]},"server_port":31002,"skipped":{"res://test/LogicGraph/LogicGraphCore/logic_graph_component_test.gd":[]},"version":"1.0"}
```

Then I met this error:
```
Debugger Break, Reason: 'not enough arguments for format string in operator '%'.'
*Frame 0 - res://addons/gdUnit4/bin/GdUnitCmdTool.gd:406 in function 'skip_suite'

code line 406: _console.prints_warning("Skip test suite %s:%s" % suite_to_skip)
```
